src/Entity/BankAccount.php
<?php

namespace App\Entity;

use App\Enum\BankAccountStatus;
use App\Enum\BankAccountType;
use App\Repository\BankAccountRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BankAccountRepository::class)]
class BankAccount
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'bankAccounts', fetch: 'EAGER')] // Activation du chargement immédiat
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    #[ORM\Column(type: 'string', enumType: BankAccountType::class)]
    private BankAccountType $type;

    #[ORM\Column(type: 'string', enumType: BankAccountStatus::class)]
    private BankAccountStatus $status;

    #[ORM\Column(type: 'string')]
    private string $account_number;

    #[ORM\Column(type: 'float')]
    private float $balance = 100.00;

    #[ORM\OneToMany(targetEntity: Transaction::class, mappedBy: 'source_account')]
    private Collection $transactions_issued;

    #[ORM\OneToMany(targetEntity: Transaction::class, mappedBy: 'destination_account')]
    private Collection $transactions_received;

    public function __construct()
    {
        $this->transactions_issued = new ArrayCollection();
        $this->transactions_received = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): static
    {
        $this->owner = $owner;

        return $this;
    }

    public function getType(): BankAccountType
    {
        return $this->type;
    }

    public function setType(BankAccountType $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getStatus(): BankAccountStatus
    {
        return $this->status;
    }

    public function setStatus(BankAccountStatus $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getAccountNumber(): string
    {
        return $this->account_number;
    }

    public function setAccountNumber(string $account_number): static
    {
        $this->account_number = $account_number;

        return $this;
    }

    public function getBalance(): float
    {
        return $this->balance;
    }

    public function setBalance(float $balance): static
    {
        $this->balance = $balance;

        return $this;
    }

    public function getTransactionsIssued(): Collection
    {
        return $this->transactions_issued;
    }

    public function addTransactionsIssued(Transaction $transactionsIssued): static
    {
        if (!$this->transactions_issued->contains($transactionsIssued)) {
            $this->transactions_issued->add($transactionsIssued);
            $transactionsIssued->setSourceAccount($this);
        }

        return $this;
    }

    public function canWithdraw(float $amount): bool
    {
        if ($this->type === BankAccountType::CURRENT) {
            return ($this->balance - $amount >= -400);
        }

        return ($this->balance - $amount >= 0);
    }

    public function canDeposit(float $amount): bool
    {
        if ($this->type === BankAccountType::SAVINGS) {
            return ($this->balance + $amount <= 25000);
        }

        return true;
    }

    public function removeTransactionsIssued(Transaction $transactionsIssued): static
    {
        if ($this->transactions_issued->removeElement($transactionsIssued)) {
            if ($transactionsIssued->getSourceAccount() === $this) {
                $transactionsIssued->setSourceAccount(null);
            }
        }

        return $this;
    }

    public function getTransactionsReceived(): Collection
    {
        return $this->transactions_received;
    }

    public function isActive(): bool
    {
        return $this->status === BankAccountStatus::ACTIVE;
    }

    public function addTransactionsReceived(Transaction $transactionsReceived): static
    {
        if (!$this->transactions_received->contains($transactionsReceived)) {
            $this->transactions_received->add($transactionsReceived);
            $transactionsReceived->setDestinationAccount($this);
        }

        return $this;
    }

    public function removeTransactionsReceived(Transaction $transactionsReceived): static
    {
        if ($this->transactions_received->removeElement($transactionsReceived)) {
            if ($transactionsReceived->getDestinationAccount() === $this) {
                $transactionsReceived->setDestinationAccount(null);
            }
        }

        return $this;
    }
}

src/Entity/Transaction.php
<?php

namespace App\Entity;

use App\Enum\TransactionStatus;
use App\Enum\TransactionType;
use App\Repository\TransactionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TransactionRepository::class)]
class Transaction
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'string', enumType: TransactionType::class)]
    private TransactionType $type;

    #[ORM\Column]
    private ?int $amount = null;

    #[ORM\Column(type: 'string', enumType: TransactionStatus::class)]
    private TransactionStatus $status;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_time = null;

    #[ORM\ManyToOne(targetEntity: BankAccount::class, inversedBy: 'transactions_issued')]
    #[ORM\JoinColumn(nullable: true)]
    private ?BankAccount $source_account = null;

    #[ORM\ManyToOne(targetEntity: BankAccount::class, inversedBy: 'transactions_received')]
    #[ORM\JoinColumn(nullable: true)]
    private ?BankAccount $destination_account = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?TransactionType
    {
        return $this->type;
    }

    public function setType(TransactionType  $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(int $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getStatus(): ?TransactionStatus
    {
        return $this->status;
    }

    public function setStatus(TransactionStatus $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->date_time;
    }

    public function setDateTime(\DateTimeInterface $date_time): static
    {
        $this->date_time = $date_time;

        return $this;
    }

    public function getSourceAccount(): ?BankAccount
    {
        return $this->source_account;
    }

    public function setSourceAccount(?BankAccount $source_account): static
    {
        $this->source_account = $source_account;

        return $this;
    }

    public function getDestinationAccount(): ?BankAccount
    {
        return $this->destination_account;
    }

    public function setDestinationAccount(?BankAccount $destination_account): static
    {
        $this->destination_account = $destination_account;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $firstName = null;

    #[ORM\Column(length: 50)]
    private ?string $lastName = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private ?string $phone = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column]
    private ?string $password = null;

    #[ORM\OneToMany(targetEntity: BankAccount::class, mappedBy: 'owner')]
    private Collection $bankAccounts;

    /**
     * @var Collection<int, Beneficiary>
     */
    #[ORM\OneToMany(targetEntity: Beneficiary::class, mappedBy: 'member', orphanRemoval: true)]
    private Collection $beneficiary;

    public function __construct()
    {
        $this->bankAccounts = new ArrayCollection();
        $this->beneficiary = new ArrayCollection();
    }

    public function getFirstName(): ?string {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self {
        $this->firstName = $firstName;
        return $this;
    }

    public function getLastName(): ?string {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self {
        $this->lastName = $lastName;
        return $this;
    }

    public function getPhone(): ?string {
        return $this->phone;
    }

    public function setPhone(?string $phone): void {
        $this->phone = $phone;
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getEmail(): ?string {
        return $this->email;
    }
    public function getName(): ?string
    {
        return $this->firstName . ' ' . $this->lastName;
    }
    
    public function setEmail(string $email): static {
        $this->email = $email;
        return $this;
    }

    public function getUserIdentifier(): string {
        return (string) $this->email;
    }

    public function getRoles(): array {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }

    public function setRoles(array $roles): static {
        $this->roles = $roles;
        return $this;
    }

    public function getPassword(): ?string {
        return $this->password;
    }

    public function setPassword(string $password): static {
        $this->password = $password;
        return $this;
    }

    public function eraseCredentials(): void {}

    public function getBankAccounts(): Collection {
        return $this->bankAccounts;
    }

    public function addBankAccount(BankAccount $bankAccount): static {
        if (!$this->bankAccounts->contains($bankAccount)) {
            $this->bankAccounts->add($bankAccount);
            $bankAccount->setOwner($this);
        }
        return $this;
    }

    public function removeBankAccount(BankAccount $bankAccount): static {
        if ($this->bankAccounts->removeElement($bankAccount)) {
            if ($bankAccount->getOwner() === $this) {
                $bankAccount->setOwner(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection<int, Beneficiary>
     */
    public function getBeneficiary(): Collection
    {
        return $this->beneficiary;
    }

    public function addBeneficiary(Beneficiary $beneficiary): static
    {
        if (!$this->beneficiary->contains($beneficiary)) {
            $this->beneficiary->add($beneficiary);
            $beneficiary->setMember($this);
        }

        return $this;
    }

    public function removeBeneficiary(Beneficiary $beneficiary): static
    {
        if ($this->beneficiary->removeElement($beneficiary)) {
            if ($beneficiary->getMember() === $this) {
                $beneficiary->setMember(null);
            }
        }

        return $this;
    }

}

src/Controller/UserController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;


final class UserController extends AbstractController
{
    #[Route('/user', name: 'customer_dashboard')]
    public function index(
       
    ): Response {
        $user = $this->getUser(); 

        if (!$user) {
            throw $this->createAccessDeniedException("Vous devez être connecté pour accéder à cette page.");
        }

       
        return $this->render('user/index.html.twig', [
            'user' => $user,
        ]);
    }
}

templates/user/accountTransactions.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Transactions{% endblock %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100">

    {% block body %}
        <!-- Barre de navigation -->
        <header class="bg-green-700 text-white p-4 shadow-md">
            <div class="container mx-auto flex justify-between items-center">
                <a href="{{ path('user_accounts') }}" class="text-lg font-semibold">Mes Comptes</a>
                <div class="flex items-center space-x-4">
                    <a href="{{ path('app_logout') }}" class="bg-red-500 hover:bg-red-700 text-white px-4 py-2 rounded-md transition">Déconnexion</a>
                    <img src="{{ asset('images/profile-placeholder.png') }}" alt="Photo de profil" class="w-10 h-10 rounded-full border-2 border-white">
                </div>
            </div>
        </header>

        <!-- Contenu principal -->
        <div class="container mx-auto mt-10 p-4">
            <!-- Onglets (Withdraw, Deposit, Transfer) -->
            <div class="flex justify-center space-x-4 mb-6">
                <a href="{{ path('app_withdraw') }}" class="bg-blue-500 hover:bg-blue-700 text-white px-6 py-2 rounded-md transition">Retrait</a>
                <a href="{{ path('app_deposit') }}" class="bg-green-500 hover:bg-green-700 text-white px-6 py-2 rounded-md transition">Dépôt</a>
                <a href="{{ path('app_transfer') }}" class="bg-yellow-500 hover:bg-yellow-700 text-white px-6 py-2 rounded-md transition">Virement</a>
            </div>

            <!-- Liste des transactions -->
            <h3 class="text-2xl font-semibold text-gray-800 mb-4">Historique des Transactions</h3>

            <div class="bg-white shadow-md rounded-lg p-6">
                <ul class="divide-y divide-gray-200">
                    {% for transaction in transactions %}
                        <li class="py-4 flex justify-between items-center">
                            <div>
                                <span class="text-gray-500">{{ transaction.dateTime|date('d/m/Y H:i') }}</span>
                                <span class="font-semibold ml-2">{{ transaction.type.value }}</span>
                            </div>
                            <div class="text-lg font-bold {% if transaction.amount < 0 %}text-red-500{% else %}text-green-500{% endif %}">
                                {{ transaction.amount|number_format(2, ',', ' ') }} €
                            </div>
                            <span class="px-3 py-1 rounded-md text-white text-sm {% if transaction.status.value == 'validée' %}bg-green-500{% else %}bg-gray-500{% endif %}">
                                {{ transaction.status.value }}
                            </span>
                        </li>
                    {% else %}
                        <li class="text-center text-gray-500 py-6">Aucune transaction trouvée.</li>
                    {% endfor %}
                </ul>
            </div>

            <!-- Pagination -->
            <div class="flex justify-between items-center mt-6">
                <button class="bg-gray-300 hover:bg-gray-400 px-4 py-2 rounded-md transition" id="prev-page">Précédent</button>
                <span id="page-info" class="text-gray-700">Page 1</span>
                <button class="bg-gray-300 hover:bg-gray-400 px-4 py-2 rounded-md transition" id="next-page">Suivant</button>
            </div>
        </div>

    {% endblock %}

</body>
</html>

templates/user/userAccounts.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mes Comptes{% endblock %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100">

    {% block body %}
        <header class="bg-green-700 text-white p-4 shadow-md">
            <div class="container mx-auto flex justify-between items-center">
                <h1 class="text-2xl font-bold">Banque en ligne</h1>
                <div class="flex items-center space-x-4">
                    <a href="{{ path('app_logout') }}" class="bg-red-500 hover:bg-red-700 text-white px-4 py-2 rounded-md transition">Déconnexion</a>
                    <img src="{{ asset('images/profile-placeholder.png') }}" alt="Photo de profil" class="w-10 h-10 rounded-full border-2 border-white">
                </div>
            </div>
        </header>

        <div class="container mx-auto mt-10 p-4">
            <h2 class="text-3xl font-semibold text-gray-800 mb-6">Mes Comptes</h2>

            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {% for account in bankAccounts %}
                    <div class="bg-white shadow-lg rounded-lg p-6 border-l-4 {{ account.status.value == 'active' ? 'border-green-500' : 'border-red-500' }}">
                        <h3 class="text-lg font-bold text-gray-700">Compte {{ account.accountNumber }}</h3>
                        <p class="text-gray-500">Type : <span class="font-semibold">{{ account.type.value }}</span></p>
                        <p class="text-gray-500">Solde : <span class="font-semibold">{{ account.balance|number_format(2, ',', ' ') }} €</span></p>
                        <p class="mt-2">
                            État : 
                            <span class="px-2 py-1 rounded-md text-white text-sm {{ account.status.value == 'active' ? 'bg-green-500' : 'bg-red-500' }}">
                                {{ account.status.value | capitalize }}
                            </span>
                        </p>
                        <a href="{{ path('user_account_transactions', { accountId: account.id }) }}" class="mt-4 inline-block bg-blue-500 hover:bg-blue-700 text-white px-4 py-2 rounded-md transition">Voir les transactions</a>
                    </div>
                {% else %}
                    <p class="text-gray-600 col-span-full text-center">Aucun compte disponible.</p>
                {% endfor %}
            </div>
        </div>

    {% endblock %}

</body>
</html>